version: '3.8'

services:
  app:
    build: .
    environment:
      GRPC-ADDR: expenses-app-1
      PORT: 8080
      ENV: development
      PUB_HOST: kafka-node
      PUB_PORT: 9092
      MONGO_USERNAME: harry
      MONGO_PASSWORD: password
      MONGO_DATABASE: notifications
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
    ports:
    - "8082:8080"
    networks:
    - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: harry
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: notifications
    ports:
    - "27017:27017"
    networks:
    - app-network

networks:
  app-network:
    name: expenses_app-network