apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifier
  name: notifier
  namespace: default
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: notifier
  type: ClusterIP